-- =============================================
-- Script: 05-create-sales-tables.sql
-- Description: Creates sales module tables (NOT part of generic CRUD)
-- Author: Solis Team
-- Date: 2024-12-04
-- Note: Run this AFTER 04-seed-demo-tenant.sql for demo tenant
-- =============================================

-- This script creates sales-related tables in the tenant schema
-- These tables are NOT managed by the generic CRUD system
-- They have specific business logic and endpoints

-- Replace 'tenant_demo' with your actual tenant schema name
-- For other tenants, run: SELECT create_sales_tables('tenant_<name>');

CREATE OR REPLACE FUNCTION create_sales_tables(p_schema_name VARCHAR)
RETURNS VOID AS $$
BEGIN
    
    -- =============================================
    -- SALES TABLE (Header da venda)
    -- =============================================
    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.sales (
            id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            client_sale_id UUID NULL,
            store_id UUID NOT NULL,
            pos_id UUID NULL,
            operator_id UUID NULL,
            sale_datetime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            status VARCHAR(50) NOT NULL DEFAULT ''pending'',
            subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
            discount_total NUMERIC(12,2) NOT NULL DEFAULT 0,
            tax_total NUMERIC(12,2) NOT NULL DEFAULT 0,
            total NUMERIC(12,2) NOT NULL DEFAULT 0,
            payment_status VARCHAR(50) NOT NULL DEFAULT ''unpaid'',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            
            CONSTRAINT fk_sales_store FOREIGN KEY (store_id) 
                REFERENCES %I.stores(id) ON DELETE RESTRICT,
            CONSTRAINT fk_sales_operator FOREIGN KEY (operator_id) 
                REFERENCES %I.users(id) ON DELETE SET NULL,
            CONSTRAINT chk_sales_status CHECK (status IN (''pending'', ''completed'', ''canceled'', ''processing'')),
            CONSTRAINT chk_sales_payment_status CHECK (payment_status IN (''unpaid'', ''partial'', ''paid'', ''refunded'')),
            CONSTRAINT chk_sales_totals CHECK (
                subtotal >= 0 AND 
                discount_total >= 0 AND 
                tax_total >= 0 AND 
                total >= 0
            )
        )', p_schema_name, p_schema_name, p_schema_name);
    
    -- Indexes for sales table
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_sales_client_sale_id ON %I.sales(client_sale_id) WHERE client_sale_id IS NOT NULL', p_schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_sales_store_datetime ON %I.sales(store_id, sale_datetime DESC)', p_schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_sales_datetime ON %I.sales(sale_datetime DESC)', p_schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_sales_status ON %I.sales(status)', p_schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_sales_payment_status ON %I.sales(payment_status)', p_schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_sales_operator ON %I.sales(operator_id)', p_schema_name);
    
    -- Trigger for sales updated_at
    EXECUTE format('
        DROP TRIGGER IF EXISTS trg_sales_updated_at ON %I.sales;
        CREATE TRIGGER trg_sales_updated_at
            BEFORE UPDATE ON %I.sales
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column()', p_schema_name, p_schema_name);
    
    EXECUTE format('COMMENT ON TABLE %I.sales IS ''Sales header table for tenant %I - Managed by specific sales endpoints''', p_schema_name, p_schema_name);
    EXECUTE format('COMMENT ON COLUMN %I.sales.client_sale_id IS ''UUID generated by POS/client for offline sync and idempotency''', p_schema_name);
    
    -- =============================================
    -- SALE_ITEMS TABLE (Itens da venda)
    -- =============================================
    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.sale_items (
            id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            sale_id UUID NOT NULL,
            product_id UUID NOT NULL,
            sku VARCHAR(100) NULL,
            description TEXT NULL,
            quantity NUMERIC(12,4) NOT NULL,
            unit_price NUMERIC(12,4) NOT NULL,
            discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
            tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
            total NUMERIC(12,2) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            
            CONSTRAINT fk_sale_items_sale FOREIGN KEY (sale_id) 
                REFERENCES %I.sales(id) ON DELETE CASCADE,
            CONSTRAINT fk_sale_items_product FOREIGN KEY (product_id) 
                REFERENCES %I.products(id) ON DELETE RESTRICT,
            CONSTRAINT chk_sale_items_quantity CHECK (quantity > 0),
            CONSTRAINT chk_sale_items_unit_price CHECK (unit_price >= 0),
            CONSTRAINT chk_sale_items_amounts CHECK (
                discount_amount >= 0 AND 
                tax_amount >= 0 AND 
                total >= 0
            )
        )', p_schema_name, p_schema_name, p_schema_name);
    
    -- Indexes for sale_items table
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_sale_items_sale ON %I.sale_items(sale_id)', p_schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_sale_items_product ON %I.sale_items(product_id)', p_schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_sale_items_sku ON %I.sale_items(sku) WHERE sku IS NOT NULL', p_schema_name);
    
    EXECUTE format('COMMENT ON TABLE %I.sale_items IS ''Sale items table for tenant %I''', p_schema_name, p_schema_name);
    
    -- =============================================
    -- SALE_PAYMENTS TABLE (Pagamentos da venda)
    -- =============================================
    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.sale_payments (
            id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            sale_id UUID NOT NULL,
            payment_type VARCHAR(50) NOT NULL,
            amount NUMERIC(12,2) NOT NULL,
            acquirer_txn_id VARCHAR(200) NULL,
            authorization_code VARCHAR(200) NULL,
            change_amount NUMERIC(12,2) NULL,
            status VARCHAR(50) NOT NULL DEFAULT ''processed'',
            processed_at TIMESTAMPTZ NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            
            CONSTRAINT fk_sale_payments_sale FOREIGN KEY (sale_id) 
                REFERENCES %I.sales(id) ON DELETE CASCADE,
            CONSTRAINT chk_sale_payments_amount CHECK (amount > 0),
            CONSTRAINT chk_sale_payments_change CHECK (change_amount IS NULL OR change_amount >= 0),
            CONSTRAINT chk_sale_payments_status CHECK (status IN (''pending'', ''processed'', ''failed'', ''reversed''))
        )', p_schema_name, p_schema_name);
    
    -- Indexes for sale_payments table
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_sale_payments_sale ON %I.sale_payments(sale_id)', p_schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_sale_payments_type ON %I.sale_payments(payment_type)', p_schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_sale_payments_status ON %I.sale_payments(status)', p_schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_sale_payments_acquirer_txn ON %I.sale_payments(acquirer_txn_id) WHERE acquirer_txn_id IS NOT NULL', p_schema_name);
    
    EXECUTE format('COMMENT ON TABLE %I.sale_payments IS ''Sale payments table for tenant %I''', p_schema_name, p_schema_name);
    EXECUTE format('COMMENT ON COLUMN %I.sale_payments.payment_type IS ''Payment type: cash, card, pix, voucher, etc''', p_schema_name);
    
    -- =============================================
    -- SALE_TAXES TABLE (Impostos aplicados por item)
    -- =============================================
    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.sale_taxes (
            id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            sale_item_id UUID NOT NULL,
            tax_type_id UUID NOT NULL,
            tax_rule_id UUID NULL,
            base_amount NUMERIC(12,2) NOT NULL,
            rate NUMERIC(10,4) NOT NULL,
            amount NUMERIC(12,2) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            
            CONSTRAINT fk_sale_taxes_item FOREIGN KEY (sale_item_id) 
                REFERENCES %I.sale_items(id) ON DELETE CASCADE,
            CONSTRAINT fk_sale_taxes_type FOREIGN KEY (tax_type_id) 
                REFERENCES %I.tax_types(id) ON DELETE RESTRICT,
            CONSTRAINT fk_sale_taxes_rule FOREIGN KEY (tax_rule_id) 
                REFERENCES %I.tax_rules(id) ON DELETE SET NULL,
            CONSTRAINT chk_sale_taxes_base CHECK (base_amount >= 0),
            CONSTRAINT chk_sale_taxes_rate CHECK (rate >= 0),
            CONSTRAINT chk_sale_taxes_amount CHECK (amount >= 0)
        )', p_schema_name, p_schema_name, p_schema_name, p_schema_name);
    
    -- Indexes for sale_taxes table
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_sale_taxes_item ON %I.sale_taxes(sale_item_id)', p_schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_sale_taxes_type ON %I.sale_taxes(tax_type_id)', p_schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_sale_taxes_rule ON %I.sale_taxes(tax_rule_id) WHERE tax_rule_id IS NOT NULL', p_schema_name);
    
    EXECUTE format('COMMENT ON TABLE %I.sale_taxes IS ''Tax calculations per sale item for tenant %I''', p_schema_name, p_schema_name);
    EXECUTE format('COMMENT ON COLUMN %I.sale_taxes.tax_rule_id IS ''Reference to the tax rule used for calculation (NULL if manual or fallback)''', p_schema_name);
    
    -- =============================================
    -- SALE_CANCELLATIONS TABLE (Cancelamentos)
    -- =============================================
    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.sale_cancellations (
            id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            sale_id UUID NOT NULL,
            operator_id UUID NULL,
            reason TEXT NULL,
            canceled_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            source VARCHAR(50) NULL,
            cancellation_type VARCHAR(50) NOT NULL DEFAULT ''total'',
            refund_amount NUMERIC(12,2) NULL,
            payment_reversal_id UUID NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            
            CONSTRAINT fk_sale_cancellations_sale FOREIGN KEY (sale_id) 
                REFERENCES %I.sales(id) ON DELETE CASCADE,
            CONSTRAINT fk_sale_cancellations_operator FOREIGN KEY (operator_id) 
                REFERENCES %I.users(id) ON DELETE SET NULL,
            CONSTRAINT chk_sale_cancellations_type CHECK (cancellation_type IN (''total'', ''partial'')),
            CONSTRAINT chk_sale_cancellations_source CHECK (source IS NULL OR source IN (''api'', ''pos'', ''system'', ''admin'')),
            CONSTRAINT chk_sale_cancellations_refund CHECK (refund_amount IS NULL OR refund_amount >= 0)
        )', p_schema_name, p_schema_name, p_schema_name);
    
    -- Indexes for sale_cancellations table
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_sale_cancellations_sale ON %I.sale_cancellations(sale_id)', p_schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_sale_cancellations_operator ON %I.sale_cancellations(operator_id)', p_schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_sale_cancellations_date ON %I.sale_cancellations(canceled_at DESC)', p_schema_name);
    
    EXECUTE format('COMMENT ON TABLE %I.sale_cancellations IS ''Sale cancellation records for tenant %I''', p_schema_name, p_schema_name);
    EXECUTE format('COMMENT ON COLUMN %I.sale_cancellations.source IS ''Origin of cancellation: api, pos, system, admin''', p_schema_name);
    
    RAISE NOTICE 'Sales tables created successfully for schema: %', p_schema_name;
    
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION create_sales_tables(VARCHAR) IS 'Creates all sales-related tables in the specified tenant schema';

-- Create sales tables for demo tenant
SELECT create_sales_tables('tenant_demo');
