using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SolisApi.Models;

/// <summary>
/// Sale Aggregate Root (DDD)
/// Manages sale items, payments, and cancellation
/// Ensures business rules and invariants
/// </summary>
[Table("sales")]
public class Sale : Entity
{
    [Required]
    [Column("order_number")]
    public int OrderNumber { get; set; }
    
    [Column("client_sale_id")]
    public Guid? ClientSaleId { get; set; } // UUID generated by POS for offline sync

    [Required]
    [Column("store_id")]
    public Guid StoreId { get; set; }

    [Column("operator_id")]
    public Guid? OperatorId { get; set; }

    [Column("cash_register_id")]
    public Guid? CashRegisterId { get; set; }

    [Required]
    [Column("sale_datetime")]
    public DateTime SaleDateTime { get; set; } = DateTime.UtcNow;

    [Required]
    [MaxLength(50)]
    [Column("status")]
    public string Status { get; private set; } = SaleStatuses.Pending;

    [Required]
    [Column("subtotal", TypeName = "numeric(12,2)")]
    public decimal Subtotal { get; private set; }

    [Required]
    [Column("discount_total", TypeName = "numeric(12,2)")]
    public decimal DiscountTotal { get; private set; }

    [Required]
    [Column("tax_total", TypeName = "numeric(12,2)")]
    public decimal TaxTotal { get; private set; }

    [Required]
    [Column("total", TypeName = "numeric(12,2)")]
    public decimal Total { get; private set; }

    [Required]
    [MaxLength(50)]
    [Column("payment_status")]
    public string PaymentStatus { get; private set; } = PaymentStatuses.Unpaid;

    // Navigation properties (protected set para controle do aggregate)
    private readonly List<SaleItem> _items = new();
    public IReadOnlyCollection<SaleItem> Items => _items.AsReadOnly();

    private readonly List<SalePayment> _payments = new();
    public IReadOnlyCollection<SalePayment> Payments => _payments.AsReadOnly();

    public SaleCancellation? Cancellation { get; private set; }

    // Factory method
    public static Sale Create(
        Guid storeId,
        Guid? operatorId,
        Guid? clientSaleId = null,
        DateTime? saleDateTime = null,
        Guid? cashRegisterId = null)
    {
        var sale = new Sale
        {
            Id = Guid.NewGuid(),
            StoreId = storeId,
            OperatorId = operatorId,
            ClientSaleId = clientSaleId,
            SaleDateTime = saleDateTime ?? DateTime.UtcNow,
            CashRegisterId = cashRegisterId,
            Status = SaleStatuses.Pending,
            PaymentStatus = PaymentStatuses.Unpaid,
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };

        return sale;
    }

    // Add item with taxes
    public void AddItem(SaleItem item)
    {
        if (Status == SaleStatuses.Canceled)
            throw new InvalidOperationException("Cannot add items to a canceled sale");

        if (Status == SaleStatuses.Completed)
            throw new InvalidOperationException("Cannot add items to a completed sale");

        item.SaleId = Id;
        _items.Add(item);
        RecalculateTotals();
    }

    // Add payment
    public void AddPayment(SalePayment payment)
    {
        if (Status == SaleStatuses.Canceled)
            throw new InvalidOperationException("Cannot add payments to a canceled sale");

        payment.SaleId = Id;
        _payments.Add(payment);
        UpdatePaymentStatus();
    }

    // Cancel sale
    public void Cancel(string reason, string source, string cancellationType, decimal? refundAmount = null)
    {
        if (Status == SaleStatuses.Canceled)
            throw new InvalidOperationException("Sale is already canceled");

        Status = SaleStatuses.Canceled;
        Cancellation = new SaleCancellation
        {
            Id = Guid.NewGuid(),
            SaleId = Id,
            Reason = reason,
            Source = source,
            CancellationType = cancellationType,
            RefundAmount = refundAmount,
            CanceledAt = DateTime.UtcNow,
            CreatedAt = DateTime.UtcNow
        };
        UpdatedAt = DateTime.UtcNow;
    }

    // Update status
    public void UpdateStatus(string newStatus)
    {
        if (Status == SaleStatuses.Canceled)
            throw new InvalidOperationException("Cannot change status of a canceled sale");

        var validStatuses = new[] { SaleStatuses.Pending, SaleStatuses.Completed, SaleStatuses.Canceled, SaleStatuses.Processing };
        if (!validStatuses.Contains(newStatus))
            throw new ArgumentException($"Invalid status: {newStatus}");

        Status = newStatus;
        UpdatedAt = DateTime.UtcNow;

        // Auto-complete if fully paid
        if (PaymentStatus == "paid" && Status == "pending")
            Status = "completed";
    }

    // Recalculate all totals (taxes are informational for NFC-e, not added to financial total)
    private void RecalculateTotals()
    {
        Subtotal = _items.Sum(i => i.Quantity * i.UnitPrice);
        DiscountTotal = _items.Sum(i => i.DiscountAmount);
        TaxTotal = _items.Sum(i => i.TaxAmount);
        Total = Subtotal - DiscountTotal;
        UpdatedAt = DateTime.UtcNow;
    }



    // Update payment status based on payments
    private void UpdatePaymentStatus()
    {
        var totalPaid = _payments.Where(p => p.Status == PaymentProcessingStatuses.Processed).Sum(p => p.Amount);

        if (totalPaid >= Total)
        {
            PaymentStatus = PaymentStatuses.Paid;
            if (Status == SaleStatuses.Pending)
                Status = SaleStatuses.Completed;
        }
        else if (totalPaid > 0)
        {
            PaymentStatus = PaymentStatuses.Partial;
        }
        else
        {
            PaymentStatus = PaymentStatuses.Unpaid;
        }

        UpdatedAt = DateTime.UtcNow;
    }

    // Required by EF Core — not for domain use
    protected Sale() { }
}
